[redis]
host: "127.0.01"
port: 6379
username = "ruckus"
password = "password"
database_name = "ruckus_db"

[postgres]
host: "127.0.01"
port: 5432
username = "ruckus"
password = "password"
database_name = "ruckus_db"
